apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
{{ include "hlf-operator.labels" . | indent 6}}
  name: {{ include "hlf-operator.fullname" . }}-controller-manager
spec:
  replicas: 1
  selector:
    matchLabels:
{{ include "hlf-operator.selectorLabels" . | indent 6}}
  template:
    metadata:
      {{- with .Values.podAnnotations }}
      annotations:
  {{ toYaml . | indent 8 }}
      {{- end }}
      labels:
{{ include "hlf-operator.selectorLabels" . | indent 8 }}
    spec:
      {{- with .Values.imagePullSecrets }}
      imagePullSecrets:
      {{- toYaml . | nindent 8 }}
      {{- end }}

      containers:
        - args:
            - --secure-listen-address=0.0.0.0:8443
            - --upstream=http://127.0.0.1:8080/
            - --logtostderr=true
            - --v=10
          image: gcr.io/kubebuilder/kube-rbac-proxy:v0.5.0
          name: kube-rbac-proxy
          ports:
            - containerPort: 8443
              name: https
        - args:
            - --metrics-addr=127.0.0.1:8080
            - --enable-leader-election
  {{ if .Values.certificates.renewal.peer.enabled }}
            - --auto-renew-peer-certificates
            - "true"
            - --auto-renew-peer-certificates-delta
            - {{ .Values.certificates.renewal.peer.delta | quote }}
  {{- end }}
  {{ if .Values.certificates.renewal.orderer.enabled }}
            - --auto-renew-orderer-certificates
            - "true"
            - --auto-renew-orderer-certificates-delta
            - {{ .Values.certificates.renewal.orderer.delta | quote }}
  {{- end }}
  {{ if .Values.certificates.renewal.identity.enabled }}
            - --auto-renew-identity-certificates
            - "true"
            - --auto-renew-identity-certificates-delta
            - {{ .Values.certificates.renewal.identity.delta | quote }}
  {{- end }}
          command:
            - /hlf-operator
          image: {{.Values.image.repository}}:{{.Values.image.tag}}
          imagePullPolicy: {{.Values.image.pullPolicy | default "IfNotPresent"}}
          name: manager
          resources:
      {{- toYaml .Values.resources | nindent 12 }}
      terminationGracePeriodSeconds: 10
      {{- with .Values.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
