apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: {{ include "hlf-operator.fullname" . }}-leader-election-role

rules:
  - apiGroups:
      - ""
    resources:
      - configmaps
    verbs:
      - get
      - list
      - watch
      - create
      - update
      - patch
      - delete
  - apiGroups:
      - ""
    resources:
      - configmaps/status
    verbs:
      - get
      - update
      - patch
  - apiGroups:
      - ""
    resources:
      - events
    verbs:
      - create
      - patch
  - apiGroups:
      - gateway.networking.k8s.io
    resources:
      - gatewayclasses
      - gateways
      - httproutes
      - tcproutes
      - tlsroutes
    verbs:
      - get
      - list
      - watch
      - create
      - patch
  - apiGroups:
      - gateway.networking.k8s.io
    resources:
      - gatewayclasses/status
      - gateways/status
      - httproutes/status
      - tcproutes/status
      - tlsroutes/status
    verbs:
      - update
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: {{ include "hlf-operator.fullname" . }}-manager-role
rules:
- apiGroups:
  - ""
  resources:
  - configmaps
  - deployments
  - persistentvolumeclaims
  - pods
  - pods/log
  - pods/status
  - replicasets
  - secrets
  - serviceaccounts
  - services
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - ""
  resources:
  - nodes
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - apps
  - extensions
  resources:
  - configmaps
  - deployments
  - persistentvolumeclaims
  - pods
  - pods/log
  - pods/status
  - replicasets
  - secrets
  - services
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - coordination.k8s.io
  resources:
  - leases
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - hlf.kungfusoftware.es
  resources:
  - console
  - fabriccas
  - fabricchaincodeapproves
  - fabricchaincodecommits
  - fabricchaincodeinstalls
  - fabricchaincodes
  - fabricchaincodetemplates
  - fabricfollowerchannels
  - fabricidentities
  - fabricmainchannels
  - fabricnetworkconfigs
  - fabricoperationsconsoles
  - fabricoperatorapis
  - fabricoperatoruis
  - fabricorderernodes
  - fabricorderingservices
  - fabricpeers
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - hlf.kungfusoftware.es
  resources:
  - console/finalizers
  - console/status
  - fabriccas/finalizers
  - fabriccas/status
  - fabricchaincodeapproves/finalizers
  - fabricchaincodeapproves/status
  - fabricchaincodecommits/finalizers
  - fabricchaincodecommits/status
  - fabricchaincodeinstalls/finalizers
  - fabricchaincodeinstalls/status
  - fabricchaincodes/finalizers
  - fabricchaincodes/status
  - fabricchaincodetemplates/finalizers
  - fabricchaincodetemplates/status
  - fabricfollowerchannels/finalizers
  - fabricfollowerchannels/status
  - fabricidentities/finalizers
  - fabricidentities/status
  - fabricmainchannels/finalizers
  - fabricmainchannels/status
  - fabricnetworkconfigs/finalizers
  - fabricnetworkconfigs/status
  - fabricoperationsconsoles/finalizers
  - fabricoperationsconsoles/status
  - fabricoperatorapis/finalizers
  - fabricoperatorapis/status
  - fabricoperatoruis/finalizers
  - fabricoperatoruis/status
  - fabricorderernodes/finalizers
  - fabricorderernodes/status
  - fabricorderingservices/finalizers
  - fabricorderingservices/status
  - fabricpeers/finalizers
  - fabricpeers/status
  verbs:
  - get
  - patch
  - update
- apiGroups:
  - monitoring.coreos.com
  resources:
  - podmonitors
  - servicemonitors
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - networking.istio.io
  resources:
  - gateways
  - virtualservices
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - rbac.authorization.k8s.io
  resources:
  - clusterrolebindings
  - clusterroles
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: {{ include "hlf-operator.fullname" . }}-proxy-role
rules:
  - apiGroups:
      - authentication.k8s.io
    resources:
      - tokenreviews
    verbs:
      - create
  - apiGroups:
      - authorization.k8s.io
    resources:
      - subjectaccessreviews
    verbs:
      - create
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: {{ include "hlf-operator.fullname" . }}-metrics-reader
rules:
  - nonResourceURLs:
      - /metrics
    verbs:
      - get
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: {{ include "hlf-operator.fullname" . }}-leader-election-rolebinding

roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: {{ include "hlf-operator.fullname" . }}-leader-election-role
subjects:
  - kind: ServiceAccount
    name: default

---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: {{ include "hlf-operator.fullname" . }}-manager-rolebinding
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: {{ include "hlf-operator.fullname" . }}-manager-role
subjects:
  - kind: ServiceAccount
    name: default
    namespace: {{.Release.Namespace}}

---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: {{ include "hlf-operator.fullname" . }}-proxy-rolebinding
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: {{ include "hlf-operator.fullname" . }}-proxy-role
subjects:
  - kind: ServiceAccount
    name: default
    namespace: {{.Release.Namespace}}

